### PR TITLE
Added Python 3.9

### PR DESCRIPTION
**Pull request by radarhere**
Updated multibuild to include Python 3.9, added a Travis job and updated the README.

### CODE REVIEW

**Comment by radarhere** [comment]
Ah. The error is from updating multibuild. It passes until https://github.com/matthew-brett/multibuild/pull/279

**Comment by matthew-brett** [comment]
Sorry to be slow - where are we with this one?

**Comment by radarhere** [comment]
The multibuild PR that I mentioned changes the default MB_PYTHON_OSX_VER. If I take the failing job and specify an OSX_VER of what it was before, 10.6, and choose a Python version that has a 10.6 package, then it passes.

**Comment by HexDecimal** [comment]
Mind if the multibuild submodule was updated to include the Pip end-of-support workarounds?  Tests for Python 2.7 and 3.5 are currently failing.

**Comment by radarhere** [comment]
You're talking about https://github.com/matthew-brett/multibuild/pull/385? I've created #98 for that, keeping things separate.

**Comment by HexDecimal** [comment]
That's correct.  I tried to do it myself but ended up encountering the same build-wheels issue mentioned here.  It seemed like mentioning the Pip issue might be better than opening a new issue for it since this PR was already updating the submodule.

**Pull request merged**
