### PR TITLE
MRG: maintenance updates for setup

### PR DESCRIPTION
**Pull request by matthew-brett**
* Update versioneer
* Require setuptools

### CODE REVIEW

**Comment by HexDecimal** [comment]
What's your progress on this PR?  Can you rebase it onto master?

**Comment by matthew-brett** [comment]
Rebased, updated to Versioneer 0.20.

**Review by HexDecimal — APPROVED** [review]
Everything looks good.  My only issues are with Versioneer itself, such as missing type annotations and not using `pyproject.toml`, stuff that I could technically fix upstream.

You can merge this PR.

**Comment by matthew-brett** [comment]
Thanks for the review.

**Pull request merged**
