### PR TITLE
Install one copy of libs used by multiple extension modules

### PR DESCRIPTION
**Pull request by lpsinger**
If you have a package that contains multiple C extensions that depend on the same shared libraries, then `delocate-wheel` saves duplicate copies of all of the shared libraries. An example is shown below.

This makes for packages that are several times larger than necessary. This patch causes `delocate-wheel` to sweep up all of the dependencies and put them in a single directory, rather than creating duplicates.

The convention is based on the proposal in pypa/auditwheel#89 and pypa/auditwheel#90.

## Example

```
gs66-wintermute:wheelhouse lpsinger$ tar tf lalsuite-6.48-cp36-cp36m-macosx_10_13_x86_64.whl 
lalsuite-6.48.dist-info/RECORD
lalsuite-6.48.dist-info/metadata.json
lalsuite-6.48.dist-info/WHEEL
lalsuite-6.48.dist-info/DESCRIPTION.rst
lalsuite-6.48.dist-info/top_level.txt
lalsuite-6.48.dist-info/METADATA
lalsimulation/_lalsimulation.cpython-36m-darwin.so
lalsimulation/__init__.py
lalsimulation/git_version.py
lalsimulation/_lalsimulation.so
lalsimulation/lalsimulation.py
lalsimulation/.dylibs/liblalsimulation.16.dylib
lalsimulation/.dylibs/libz.1.2.11.dylib
lalsimulation/.dylibs/libhdf5_hl.100.dylib
lalsimulation/.dylibs/libfftw3f.3.dylib
lalsimulation/.dylibs/libgsl.23.dylib
lalsimulation/.dylibs/liblalsupport.11.dylib
lalsimulation/.dylibs/liblal.14.dylib
lalsimulation/.dylibs/libhdf5.101.dylib
lalsimulation/.dylibs/libfftw3.3.dylib
lalsimulation/.dylibs/libgslcblas.0.dylib
lalsimulation/.dylibs/libgcc_s.1.dylib
lalmetaio/lalmetaio.py
lalmetaio/__init__.py
lalmetaio/git_version.py
lalmetaio/_lalmetaio.so
lalmetaio/_lalmetaio.cpython-36m-darwin.so
lalmetaio/.dylibs/libz.1.2.11.dylib
lalmetaio/.dylibs/liblalmetaio.5.dylib
lalmetaio/.dylibs/libmetaio.1.dylib
lalmetaio/.dylibs/libhdf5_hl.100.dylib
lalmetaio/.dylibs/libfftw3f.3.dylib
lalmetaio/.dylibs/libgsl.23.dylib
lalmetaio/.dylibs/liblalsupport.11.dylib
lalmetaio/.dylibs/liblal.14.dylib
lalmetaio/.dylibs/libhdf5.101.dylib
lalmetaio/.dylibs/libfftw3.3.dylib
lalmetaio/.dylibs/libgslcblas.0.dylib
lalmetaio/.dylibs/libgcc_s.1.dylib
...
```

### CODE REVIEW

**Comment by matthew-brett** [comment]
Thanks a lot for making this PR.  It would be excellent to get this in.   Will you have a chance to fix the test failures?  Can you think of a test for this behavior?   Maybe a fake package to delocate?

**Comment by lpsinger** [comment]
> Can you think of a test for this behavior? Maybe a fake package to delocate?

Sure. Should I put it in the `wheel_makers` directory?

Also, should the libraries go in `$PACKAGENAME.dylibs`, or `$PACKAGENAME-$VERSION.dylibs`, to mimic the versioning of .egg-info directories?

**Comment by matthew-brett** [comment]
Right - the best thing is to put the recipe in `wheel_makers/make_wheels.sh`, and modify the script to copy the new test wheels into the `tests/data' directory.

`$PACKAGENAME-$VERSION.dylibs` sounds like a better idea.  I guess pip can be relied on to uninstall correctly either way?

**Comment by lpsinger** [comment]
> I guess pip can be relied on to uninstall correctly either way?

Yes, I think so.

**Comment by lpsinger** [comment]
The comments in `make_wheels.sh` say to build on 10.6. I don't have access to a 10.6 machine. Do you have a way to do the build on travis and save the new wheels?

**Comment by matthew-brett** [comment]
I'm sorry, no, I don't have a way to do that.   We should update to something modern now, it's very hard to find 10.6 machines.

**Comment by lpsinger** [comment]
Looks like 10.10 is the oldest version supported by Travis. Is that old enough?

There ought to be some way to have Travis spit out build artifacts.

**Comment by matthew-brett** [comment]
10.10 should be fine.  We can use Rackspace to upload to (I have the API key to do that).

**Comment by lpsinger** [comment]
Great! I haven't yet added the new test, but I've gotten as far as I can with fixing the old tests without being able to regenerate the binary wheels. Would you be able to work on master to modify the travis configuration so that it deposits the test wheels on rackspace?

**Comment by matthew-brett** [comment]
Yes, sorry, I'm afraid I am hitting an extreme work slam at the moment, I will try very hard to get this at the weekend.  If you have any interest in having a go yourself, have a look at https://github.com/MacPython/atom-wheels/blob/master/.travis.yml for using wheelhouse uploader to upload to rackspace.  I have added the encrypted key, in the meantime, to master, in case you want to try it.  Actually, I think it won't upload unless from my branch, but at least you maybe see what needs doing.

**Comment by lpsinger** [comment]
OK, I tried, but it's saying:

    WARNING: secret API key missing: skipping package upload

I'm not sure where to look for the uploaded wheels, either.

**Comment by lpsinger** [comment]
Any hints on how to upload the test wheels? I'm afraid that I need some help to push this over the finish line.

**Comment by HexDecimal** [comment]
This PR is no longer needed since #123 was merged.  That PR fixed #35 by always using a single dylibs directory for the entire wheel.

**Pull request closed without merging**
