### PR TITLE
MRG: Sketch of mock testing for get_install_names

### PR DESCRIPTION
**Pull request by matthew-brett**
Use mock to simulate otool output for get_install_names

### CODE REVIEW

**Comment by HexDecimal** [comment]
Add `# noqa: E501` to the lines you close the multi-line strings with since there isn't a graceful way to shorten them.  Running black should resolve any remaining formatting issues.

**Comment by matthew-brett** [comment]
Done.

**Comment by matthew-brett** [comment]
I added testing for Rpaths and install IDs.  It's a bit verbose, but I think it is better than not testing, and it does give a template for Otool output difference testing.

**Comment by HexDecimal** [comment]
I've just pushed a significant refactor to this PR, solving every issue I had with it.  If you approve of my changes then this is should be merged.

**Review by matthew-brett — COMMENTED** [review]
Looks good to me.  Did you test that the tests fail when the inputs are not as expected?

**Comment by HexDecimal** [comment]
I'm not sure what you mean.  The mock is more strict requiring that `example.so` be the file tested, so changing that will fail the tests.  Changing the mocked outputs will fail tests if the changed parts are relevant to the called functions.  The parametrized tests will show which `ToolArchMock` failed to pass.

**Comment by matthew-brett** [comment]
OK - I spent some time randomly deleting and modifying the `ToolArchMock` entries and confirming that the test fails.

**Pull request merged**
