### PR TITLE
fix for files with architecture name appended in install_name

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Review by matthew-brett — COMMENTED** [review]
Would you mind adding a test?  Can you work out a way of making a file that does return a relevant line from `otool` and put that into the `make_libs.sh` file in `tests/data`?  Then test in `test_install_names`?

**Comment by isuruf** [comment]
I tried, but I can't find a way. I can download one if that works.

**Comment by matthew-brett** [comment]
Do you mean - it's difficult to find a way to build a library that generates that text from `otool -L`?

If you have a small library to hand, that has a compatible license, then maybe you could add that to the PR?

**Comment by isuruf** [comment]
Found the way to create the lib and added a test. Ready for review.

**Comment by matthew-brett** [comment]
Thanks - yes - fine with me. Feel free to merge when the tests pass.

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
