### PR TITLE
Enforce type annotations.

### PR DESCRIPTION
**Pull request by HexDecimal**
This adds checks for MyPy, and ensures the `typing` and `typing_extensions` modules are available. `py.typed` marks the package as typed.

`six` wasn't added but it probably should be.  Python 2 string typing will be difficult without it.

### CODE REVIEW

**Comment by matthew-brett** [comment]
@HexDecimal - anything left here that didn't go in with #94?

**Comment by HexDecimal** [comment]
This PR still does a lot of important things, including adding Mypy to a GitHub workflow and marking Delocate as a type-checked package for scripts which import it.

I've just updated it for Python 3.6.

**Comment by matthew-brett** [comment]
Feel free to merge when tests pass.

**Comment by HexDecimal** [comment]
I'm not a maintainer with merge permissions.

**Comment by matthew-brett** [comment]
Sorry - I forgot.  I've sent you an invite.

**Pull request merged**
